version: '3.8'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      FLASK_ENV: delopment
      MPESA_API_KEY: your_mpesa_api_key
      DATABASE_URL: postgresql://user:password@db/app
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRESS_DB: app
    volumes:
      - postgres_data:/var/lib/postgressql/data
volumes:
  postgres_data: