"""Add learning_area to Grade

Revision ID: 147e7e277288
Revises: 
Create Date: 2025-07-31 08:50:21.192785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '147e7e277288'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grade', schema=None) as batch_op:
        batch_op.add_column(sa.Column('learning_area', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('strand', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('sub_strand', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('cbc_level', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('teacher_comment', sa.Text(), nullable=True))
        batch_op.drop_column('subject')
        batch_op.drop_column('score')

    with op.batch_alter_table('performances', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rank', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('summary', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('performances', schema=None) as batch_op:
        batch_op.drop_column('summary')
        batch_op.drop_column('rank')

    with op.batch_alter_table('grade', schema=None) as batch_op:
        batch_op.add_column(sa.Column('score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('subject', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.drop_column('teacher_comment')
        batch_op.drop_column('cbc_level')
        batch_op.drop_column('sub_strand')
        batch_op.drop_column('strand')
        batch_op.drop_column('learning_area')

    # ### end Alembic commands ###
