"""Allow teacher_id to be nullable in classrooms

Revision ID: 448772c1f4cb
Revises: 
Create Date: 2025-07-14 10:59:39.963445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '448772c1f4cb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('classrooms', schema=None) as batch_op:
        batch_op.alter_column('teacher_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('classrooms', schema=None) as batch_op:
        batch_op.alter_column('teacher_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
