"""Restore correct Grade model

Revision ID: 6841db5af9ef
Revises: 75576c1c1e2e
Create Date: 2025-07-15 05:47:57.335088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6841db5af9ef'
down_revision = '75576c1c1e2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('grades')
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.alter_column('class_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.alter_column('class_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    op.create_table('grades',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('subject', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('term', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('marks', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('grades_student_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('grades_pkey'))
    )
    # ### end Alembic commands ###
